#!/usr/bin/python


import requests.packages.urllib3
import pykube
import re
import argparse
import os
import csv
import json
from os import environ as env


def load_config(path):
    # Method to create API handle
    #:param path: holds the path to config file
    #:return: api
    try:

        debug_flag = os.environ.get('DEBUG_FLAG')
        if debug_flag is not None and debug_flag == 1:
            print("load_config(path): Pulling Config from %s file => %s" , path)
        api = pykube.HTTPClient(pykube.KubeConfig.from_file(path))
        return api
    except Exception as e:
        print("ERROR: Failed to retrieve pykube.KubeConfig.from_file path => %s" % str(e))
        return api


def get_projects(project_name,path,flag):
    try:
        debug_flag = os.environ.get('DEBUG_FLAG')
        if debug_flag is not None and debug_flag == 1:
            print("listing the projects  => %s", path)
        api_handle = load_config(path)
        project_met = pykube.Namespace.objects(api_handle).get(name=project_name)
        metadata_project = project_met.obj['metadata']
        metadata_dump = json.dumps(metadata_project)
        metadata_load = json.loads(metadata_dump)
        print metadata_load
        if metadata_project is not None:
            uid = metadata_project.get('uid', None)
            print uid
            name = metadata_project.get('name',None)
            print name
            annotations = metadata_project.get('annotations', {})
            if annotations:
               application_id = annotations['citeis.cisco.com/application-id']
               print("Dhara: application_id %s" % application_id)
            else:
                application_id = 'None'
                print("Dhara: application_id %s" % application_id)
            if annotations:
               application_name = annotations['citeis.cisco.com/application-name']
               print("Dhara: application_name %s" % application_name)
            else:
                application_name = 'None'
                print("Dhara: application_name %s" % application_name)

            #metadata_dump = json.dumps(metadata_project)
            #metadata_load = json.loads(metadata_dump)
            #annotations = metadata_load['annotations']
            #uid = metadata_load['uid']
            #print("Dhara: uid %s" % uid)
            #name = metadata_load['name']
            #print("Dhara: name %s" % name)
            #print("Dhara: Annotation %s" % annotations)
            # #uid = metadata_project['uid']
            # uid = metadata_project.get('uid',None)
            # print uid
            # #name = metadata_project['name']
            # name = metadata_project.get('name',None)
            # print name
            # #application_id = annotations['citeis.cisco.com/application-id']

                # annotations.get("cities.cisco.com/application-id", None):
            #if annotations is not None:
               #application_id = ['annotations']['citeis.cisco.com/application-id']
               #print("Dhara: application_id %s" % application_id)
            #else:
                 #application_id='None'
                 #print("Dhara: application_id %s" % application_id)
            #if annotations is not None:
                 #application_name = ['annotations']['citeis.cisco.com/application-name']
                 #print("Dhara: application_name %s" % application_name)
            #else:
                #application_name='None'
                #print("Dhara: application_name %s" % application_name)
            #
            # application_name =annotations['citeis.cisco.com/application-name']
            # print application_name

            project_file_text = [name, uid, application_id, application_name]
            return project_file_text
        else:
            print("No projects found")
    except Exception as e:
        print("ERROR: Failed to retrieve project list => %s" % str(e))


def get_pods(project_pod,path):
    # Method to fetch project specific POD info
    ##:param project_pod: holds project name
    #:return: pods
    try:
        debug_flag = os.environ.get('DEBUG_FLAG')
        if debug_flag is not None and debug_flag == 1:
            print("listing the pod in project  => %s" % path)
        api_handle = load_config(path)
        pods = pykube.Pod.objects(api_handle).filter(namespace=project_pod)
        if pods is not None:
            return pods
        else:
            print("No pods found")
    except Exception as e:
        print("ERROR: Failed to retrieve pods with error => %s" % str(e))

def get_image(project_img, pod, path,flag):
    # Method to get image details of application running on pod under specified project
    #:param project_img: holds project name
    #:param pod: holds pod name
    #:return: image info
    try:
        debug_flag = os.environ.get('DEBUG_FLAG')
        if debug_flag is not None and debug_flag == 1:
            print("listing the images in the pods in the project  => %s" % path)
        api = load_config(path)
        pod = pykube.Pod.objects(api).filter(namespace=project_img).get(name=pod)
        container_status = pod.obj['status']['containerStatuses'][0]
        container_dump = json.dumps(container_status)
        container_load = json.loads(container_dump)
        print("Dhara: container_load %s" % container_load)
        image = container_load['image']
        container_port = pod.obj["spec"]["containers"][0]
        container_port_dump = json.dumps(container_port)
        container_port_load = json.loads(container_port_dump)
        print("Dhara: container_port_dump %s" % container_port_dump)
        #metadata = pod.obj['metadata']
        #metadata_dump = json.dumps(metadata)
        #metadata_load = json.loads(metadata_dump)

        if container_load and image and metadata is not None:
            pod_name = metadata.get('name',None)
            print("Dhara: pod_name %s" % pod_name)
            pod_namespace = metadata.get('namespace',None)
            print("Dhara: pod_namespace %s" % pod_namespace)
            pod_stat = pod.obj['status']
            pod_status = pod_stat.get('phase', None)
            print("Dhara: pod_status %s" % pod_status)
            container_id = container_load.get('containerID',None)
            print("Dhara: container_id %s" % container_id)
            image_name = container_load.get('image',None)
            print("Dhara: image_name %s" % image_name)
            image_id = container_load.get('imageID',None)
            print("Dhara: image_id %s" % image_id)
            container_state = container_load.get('state', {}).get('running', {})
            try:
                container_exposed_port = pod.obj['spec']['containers'][0]['ports'][0]['containerPort']
            except Exception:
                container_exposed_port = 'NONE'

            if container_state:
                container_start_date = container_state['startedAt']
                print("container_start_date: image_id %s" % container_start_date)
            else:
                container_start_date ='None'
                print("container_start_date: image_id %s" % container_start_date)
                return container_start_date
            #container_port = pod.obj["spec"]["containers"][0]['ports'][0]
            #container_exposed_port = container_port_load['containerPort']
            #if container_port :
            #container_exposed_port = container_port_load['ports'][0]['containerPort']
             #   print("Dhara: container_exposed_port %s" % container_exposed_port)
            #else:
              #  container_exposed_port= 'None'
               # print("Dhara: container_exposed_port %s" % container_exposed_port)
                #return container_exposed_port

            flag_status = flag
            image_file_text = [pod_name, pod_namespace,
                                pod_status, container_id, image_name,
                               image_id, container_start_date,
                                container_exposed_port,flag_status]
            return image, image_file_text
        else:
            print("No images found")
    except Exception as e:
        print("ERROR: Failed to retrieve images with error => %s" % str(e))




def print_metadata(image_file_text, project_file_text):
    try:
        debug_flag = os.environ.get('DEBUG_FLAG')
        if debug_flag is not None and debug_flag == 1:
            print("saving the metadata into a file   => %s" % path)
        file_content = []
        if project_file_text and image_file_text is not None:
            file_content = [project_file_text + image_file_text]
        with open('cae_image_hardening.csv', 'a') as csvFile:
            writer = csv.writer(csvFile)
            writer.writerows(file_content)
        csvFile.close()
    except Exception as e:
        print("ERROR: Failed to write the output file with error => %s" % str(e))


def build_metadata(namespace, pod, path,flag):
    try:
        debug_flag = os.environ.get('DEBUG_FLAG')
        if debug_flag is not None and debug_flag == 1:
            print("building the metadata into a file   => %s" % path)
        image_values = get_image(namespace, pod, path,flag)
        image_file_text = image_values[1]
        project_file_text = get_projects(namespace, path,flag)
        print_metadata(image_file_text, project_file_text)

    except Exception as e:
        print("ERROR: Failed to build metadata with error => %s" % str(e))


def main(url,namespace):
    # Method to raise a flag when source of image used is a non-trusted one
    #:param dom_url: just a place holder
    #:param namespace: holds the name of project
    #:return: True/False
    try:
        #getting region froim the url
        if url is not None:
            url_split = url.strip().split('.')
            string = str(url_split[0])
            string_split = string.strip().split('-')
            region_name = str(string_split[2].strip())
            path = ''
            if region_name is not None:
                if region_name == "rtp":
                    path = '/home/centos/.kube/config_bp'
                elif region_name == "rcdn":
                    path = '/home/centos/.kube/conf_bp'
                elif region_name == 'alln':
                    path = '/home/centos/.kube/config_bp'

            else:
                print("No region found")
            debug_flag = os.environ.get('DEBUG_FLAG')
            if debug_flag is not None and debug_flag == 1:
                print("Check whether source of image used is a trusted one => ")
            requests.packages.urllib3.disable_warnings()
            pods_list = get_pods(namespace, path)
            exists = os.path.isfile('cae_image_hardening.csv')
            if exists:
                with open('cae_image_hardening.csv', 'r') as csvFile:
                    reader = csv.reader(csvFile, delimiter=",")
                    data = list(reader)
                    row_count = len(data)
                csvFile.close()
            else:
                row_count = 0
            file_headers = ['Tenant Name', 'Tenant ID', 'Application ID', 'Application Name', 'Pod Name',
                            'Pod Namespace',
                            'Pod Namespace', 'Container ID', 'Image Name', 'Image ID', 'Container Start Date',
                            'Container Exposed Port ','Flag']
            file_content = [file_headers]
            if row_count<=0:
                with open('cae_image_hardening.csv', 'a') as csvFile:
                    writer = csv.writer(csvFile)
                    writer.writerows(file_content)
                csvFile.close()
            if pods_list is not None:
                for pod in pods_list:
                    flag = ''
                    image_values = get_image(namespace, pod, path,flag)
                    image = image_values[0]
                    if re.match('containers.cisco.com\/*', image):
                        flag = " compliant"
                        print("Secure - %s with image: %s " % (pod, image))
                        build_metadata(namespace, pod, path,flag)
                    else:
                        flag = "non-compliant"
                        print("Not Secure! - %s with image: %s " % (pod, image))
                        build_metadata(namespace, pod, path,flag)
            else:
                print("No Pods running in the project")

    except Exception as e:
        print("ERROR: Failed to retrieve image list and pod list with error => %s" % str(e))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Identify images with insecure source')
    parser.add_argument("-u", "--domain_url", help="Domain/Region specific URL", action="store", dest="domain_url")
    parser.add_argument('-t', '--namespace', action="store", dest='namespace',
                        help='name of namespace/project to Search')

    debug_flag = os.environ.get('DEBUG_FLAG')
    args = parser.parse_args()
    url = args.domain_url
    namespace = args.namespace
    main(url, namespace)