apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "teamdbupdate"
spec:
  storageClassName: "standard"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
      
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "teamdbupdate"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "teamdbupdate"
  template:
    metadata:
      labels:
        name: "teamdbupdate"
    spec:
      containers:
        -
          name: "teamupdate"
          image: "containers.cisco.com/phuocng/phuoc:teamdbupdate"
          volumeMounts:
            - name: "storage"
              mountPath: "/opt/app-root/src/logs"
          
          imagePullPolicy: "IfNotPresent"
          securityContext:
            capabilities: {}
            privileged: false
      volumes:
        -
          name: "storage" 
          persistentVolumeClaim: 
           claimName: "teamdbupdate"

      restartPolicy: "Always"
      dnsPolicy: "ClusterFirst"
  Triggers:
    -
      type: "ConfigChange"
  strategy:
    type: "RollingUpdate"
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 420
